name: "Destroy Terraform Infrastructure"

on:
  repository_dispatch:
    branches: master 
    types: apprecode-site-destroy
  workflow_dispatch:
 
jobs:
 terraform_destroy:
   name: "tf_destroy"
   runs-on: ubuntu-latest
   defaults:
     run:
       shell: bash
       # We keep Terraform files in the terraform directory.
       working-directory: ./${{ github.event.client_payload.client }}
 
   steps:
     - name: Checkout the repository to the runner
       uses: actions/checkout@v2
 
     - name: Setup Terraform with specified version on the runner
       uses: hashicorp/setup-terraform@v2
       with:
         terraform_version: 1.2.9
    
     - name: Terraform init
       id: init
       env:
         GH_TOKEN: ${{ secrets.GH_TOKEN }}
       run: |
         export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
         export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
         terraform init

     - name: create-json
       id: create-json
       uses: jsdaniell/create-json@v1.2.2
       with:
         name: "tfvars.json"
         json: "${{ toJson(github.event.client_payload.vars) }}"

     - name: Terraform destroy
       id: destroy
       run: |
         export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
         export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
         terraform destroy -auto-approve -var-file=../tfvars.json
